---

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Add group "teeworlds"
  group: name=teeworlds

- name: Add user "teeworlds"
  user: name=teeworlds group=teeworlds

- name: Create the install directory
  file:
    path: "{{ install_path }}"
    owner: teeworlds
    group: teeworlds
    state: directory
    mode: '0755'

- name: Get and extract Teeworlds archive into /opt/
  unarchive:
    src: https://downloads.teeworlds.com/teeworlds-{{ teeworlds_version }}-linux_x86_64.tar.gz
    dest: "{{ install_path }}"
    remote_src: yes
    owner: teeworlds
    group: teeworlds
    extra_opts: [--strip-components=1]

- name: Make sure teeworlds_srv is executable
  file:
    path: "{{ install_path }}/teeworlds_srv"
    mode: '0744'

- name: Create the configuration directory
  file:
    path: /etc/teeworlds
    owner: root
    group: root
    state: directory
    mode: '0755'

- name: Copy configuration file
  template:
    src: config.cfg
    dest: /etc/teeworlds/

- name: Copy unit file
  template:
    src: teeworlds.service
    dest: /etc/systemd/system/teeworlds.service
    mode: 0644

- name: Start Teeworlds service
  systemd:
    name: teeworlds.service
    state: restarted
    enabled: yes
    daemon_reload: yes
